package ariefhermawan.pbo.pertemuan.z_4_kelima.copas_ppt.percobaan;

import java.lang.Exception;

public class Exception12MyException extends Exception {

    private String teks;

    Exception12MyException(String message) {
        this.teks = "Exception generated by\t:" + " " + message;
        System.out.println(this.teks);
    }

}

class Eksepsi {

    static void tampil(String message) throws Exception {
        System.out.println("Tampil!");
        if (message.equals("amir")) {
            throw new Exception12MyException(message);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("Ali");
            tampil("amir");
        } catch (Exception12MyException message) {
            System.out.println("Tangkap\t: " + message);
        }
    }

}